### ISSUE TITLE
[Meta] Changes to haxelib.json

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxelib#266]
A meta issue to track all discussions about changing haxelib.json,
since it's better to do all changes at once and not across several releases.
- [ ] Specify supported haxe version #234 
- [ ] The need for both a website and repository field #222 
- [ ] Post install hooks #183 
- [ ] Defines #262 
- [ ] Dependency format #238 including the use of expressions #81 

About backward compatibility, haxelib doesn't care about fields it doesn't know, so additions aren't an issue, it's only a problem for modifications like for the dependency format.
